---
output:
  pdf_document: default
  html_document: default
---
# Apresentação {.unnumbered}

:::: {.center data-latex=""}
::: {.minipage data-latex="{.7\linewidth}"}

O Boletim de Conjuntura Econômica do Estado do Tocantins é uma das atividades do Grupo \abbr{pet} de Ciências Econômicas da [abbr:@uft] e tem como objetivo apresentar a evolução das principais variáveis macroeconômicas do estado. Esta edição tem o formato com dados trimestrais e mensais de 2024, estando a periodicidade das informações limitada à divulgação de dados pelas fontes oficiais e organizações. Este ano, mais uma vez contamos com a parceria do Conselho Regional de Economia ([abbr:@coreconto]). As informações contidas são destinadas a cidadãos, gestores públicos e empresários, sendo provenientes de fontes oficiais de organizações públicas.

Os textos e as análises apresentados têm caráter informativo. Os comentários não refletem obrigatoriamente os posicionamentos públicos do [abbr:@coreconto] ou da [abbr:@uft]. As análises podem ou não sofrer alterações, caso se confirmem, são em função da revisão de dados pelas fontes no que concerne ao período da análise, ou a mudanças na conjuntura econômica e social decorrentes de atos governamentais e de forças exógenas. No mais, essa edição do Boletim traz novas informações: A Secretaria do Planejamento e Orçamento do Estado do Tocantins passou a publicar estimativas do PIB trimestral, um indicador do Produto Interno Bruto ([abbr:@pib]) confiável e publicado com aproximadamente quatro meses de defasagem. Segundo o indicador, devemos crer que a economia cresceu de 2023 para 2024 com uma taxa de crescimento de aproximadamente 7,7%.

Na publicação deste ano, o Boletim traz dados sobre ([abbr:@pib]), contas públicas, taxa de pobreza, coeficiente de Gini, mercado de trabalho, comércio exterior e agricultura. O [abbr:@pib] corresponde à soma de toda a riqueza de uma nação num determinado período de tempo. Nesta edição, apresentamos o [abbr:@pib] pelo lado da demanda e da oferta. Pelo lado da demanda, ele é constituído pela soma do consumo das famílias, governo, investimentos e exportações líquidas; pelo lado da oferta, ele é constituído pela soma de tudo o que é produzido por todos os setores.

As contas públicas estaduais, compreendem as receitas e as despesas do governo. As receitas podem ser provenientes de tributos, transferências, contribuição e de outras fontes, e as despesas, de diferentes setores, como saúde, educação, pessoal, indústria, entre outros. Inclui-se também a capacidade de pagamento do Estado, sua situação fiscal, que compreende endividamento, poupança corrente e liquidez. No campo social, temos a taxa de pobreza e o Índice de Gini. O coeficiente de Gini é uma medida utilizada para calcular a desigualdade na distribuição de renda. Varia entre zero e um: zero significa completa igualdade de renda e um, completa desigualdade. Por consequência, quanto mais próximo de um, maior é a concentração de renda.

A variável Emprego corresponde ao número de pessoas ocupadas formalmente. Apresenta o perfil do empregado (idade, gênero, etnia, grau de instruções), o saldo de emprego do Tocantins e da Região Norte bem como os setores de contratação e demissão, seguro desemprego e rendimento médio. O tópico comércio exterior traz a análise descritiva dos dados do saldo comercial em dólares de 2024. Apresenta os principais produtos exportados e importados e os países com os quais o Tocantins tem relação comercial. A agricultura apresenta informações sobre soja, milho e arroz bem como informações sobre a pecuária, em especial, a bovinocultura.

\
Prof. Dr. Nilton Marques de Oliveira -- Tutor [abbr:@pet] Ciências Econômicas

:::
::::

\thispagestyle{empty}
\twocolumn
\pagenumbering{arabic}