---
documentclass: report
output:
  pdf_document:
    template: ../template/template.tex
    pandoc_args: "--lua-filter=../filter/boletim.lua"
---

```{r setup, include=F, message=F, warning=F}
library(tidyverse)
library(knitr)
library(scales)
library(zoo)
library(ipeadatar)
library(petgg)
library(extrafont)
library(kableExtra)
library(sidrar)
library(lubridate)
library(petknitr)

petgg::set_theme(base_family = "EB Garamond")

petknitr::setup()


m <- 1000
M <- 1000000
B <- 1000000000
```

```{r saldo, fig.cap= "Saldo de Empregos", fig.subcap="Saldo Anual",fig.source = "CAGED", wrap = "open"}

# Saldo de Empregos Norte e Tocantins

tibble(
	`Região Norte` = c(2992,10913,-6623,-31590,-11238,6382,16203,23304,21840, 21150, 14806, -9390),
	Tocantins = c(221,1492,-126,-2882,-1292,1213,1774,2136,2028,1385,1062,220),
	mes = c("jan","fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez")
) %>% 
	pivot_longer(!mes, names_to = "local", values_to = "saldo") %>% 
	ggplot(aes(factor(mes, levels = c("jan","fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez")), saldo, fill = local)) +
	geom_bar(stat = "identity", position = "dodge") +
	scale_y_continuous(labels = function(n) n/m)
```

```{r saldo_setor_to}
# Saldo por Setores no Tocantins
tibble(
	Saldo = c(542,495,2979,1543,1442), 
	Setores = c("Agricultura","Indústrias", "Construção", "Comércio", "Serviços")
) %>% 
	ggplot(aes(Setores, Saldo)) +
	geom_bar(stat = "identity") +
	scale_y_continuous(labels = function(n) n/m)
```

```{r tx_desemprego_to}
# Taxa de desemprego trimestral
ipeadatar::ipeadata("PNADC_TXDES_UF") %>% 
	filter(tcode == 17) %>% 
	ggplot(aes(date, value)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
    xmax = as.Date("2019-04-01"),
    ymin = -Inf,
    ymax = Inf,
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf
	) +
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = scales::label_number(suffix = "%", accuracy = 1))
```

```{r pedido_segudo_desem}
# Pedidos Seguro desemprego trimestral

tibble(
	value = c(9833, 9833, 8832, 8784, 9642, 9324, 9155, 8182, 8785, 10642, 7535, 8072),
	trimestre = seq(as.Date("2018-01-01"), as.Date("2020-12-01"), by = "quarter")
) %>% 
	ggplot(aes(trimestre, value)) +
	geom_line() +
	scale_y_continuous(labels = function(x) x/m) +
	scale_x_date(
		breaks = scales::breaks_width("90 day"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	)
```

```{r pop_ocupada}
# População Ocupada - Tocantins Trimestral
# Força de Trabalho - Taxa de Participação
ipeadatar::ipeadata("PNADC_TXPARTFT_UF") %>% 
	filter(tcode == 17) %>% 
	ggplot(aes(date, value)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
		xmax = as.Date("2019-04-01"),
		ymin = -Inf,
		ymax = Inf
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf
	) + 
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = scales::label_number(suffix = "%", accuracy = 1))
```

```{r rend_medio}
# Rendimento médio real - trab. principal - habitual - mensal
# Trimestral
ipeadatar::ipeadata("PNADC_RENDREALPRINCEFET_UF", language = "br") %>% 
	filter(tcode %in% c(0,1,17)) %>% 
	select(date, value, uname) %>% 
	mutate(uname = case_when(
		uname == "Brasil" ~ "Brasil",
		uname == "Regiões" ~ "Região Norte",
		uname == "Estados" ~ "Tocantins"
	)) %>% 
	ggplot(aes(date, value, colour = uname)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
		xmax = as.Date("2019-04-01"),
		ymin = -Inf,
		ymax = Inf,
		colour = NA
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf,
		colour = NA
	) + 
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = function(x) x/m)
```
```{r reg_emprego}
Dados <- data.frame(taxaDesemprego = c(11,11.3,9.8,10.4,12.3,11.4,10.5,9.1,11.2,12.5,12.2,11.6),
                        Pedidos_SeguroDesemprego = c(9833,9833,8832,8784,9642,9324,9155,8182,8785,10642,7535, 8072))
    

    
    
    #Modelo/Gráfico
    
    modelo <- lm(data = Dados, formula = Pedidos_SeguroDesemprego~taxaDesemprego)
    modelo$coefficients
    summary(modelo)
    

    ggplot(Dados, aes(x = taxaDesemprego, y = Pedidos_SeguroDesemprego)) + geom_point() + geom_smooth(method = lm, se = FALSE) +
      labs(x= "Taxa de desemprego", y= "Seguro Desemprego") + theme_petgg(axis_title = T, base_family = "EB Garamond")
    
```

```{r}
# Tabelas

caged_idade <- tibble(
  carac = c("14-34", "35-65", "65+"),
  Admitidos = c(48048, 19009, 89),
  Demitidos = c(40740, 17446, 190),
  Saldo = Admitidos - Demitidos
)
caged_sexo <- tibble(
  carac = c("Homem", "Mulher"),
  Admitidos = c(46634, 20513),
  Demitidos = c(40358, 19518),
  Saldo = Admitidos - Demitidos
)
bind_rows(caged_idade, caged_sexo) %>% 
	kable(
		caption = "XXX",
		align = "lrrr",
		format.args = list(big.mark = ".", decimal.mark = ",", scientific = FALSE),
		booktabs = T,
		col.names = c("", "Admitidos", "Demitidos", "Saldo")
	) %>% 
	kable_styling(full_width = T) %>% 
	pack_rows("Idade", 1, 3) %>% 
	pack_rows("Sexo", 4, 5)
```

```{r taxa_desemprego}
df <- get_sidra(
  x = 4092,
  geo = "State",
  header = T,
  period = "201201-202004"
) %>% janitor::clean_names()

df %>% 
  filter(
    unidade_da_federacao == "Tocantins",
    condicao_em_relacao_a_forca_de_trabalho_e_condicao_de_ocupacao %in% c("Força de trabalho - desocupada", "Força de trabalho"), 
    unidade_de_medida == "Mil pessoas"
  ) %>% 
  select(trimestre_codigo, condicao_em_relacao_a_forca_de_trabalho_e_condicao_de_ocupacao, valor) %>% 
  pivot_wider(
    names_from = condicao_em_relacao_a_forca_de_trabalho_e_condicao_de_ocupacao, 
    values_from = valor
  ) %>% 
  rowwise() %>% 
  mutate(
    taxa_des = `Força de trabalho - desocupada`/ `Força de trabalho` * 100,
    quarter = trimestre_codigo %>% stringr::str_replace("(?<=\\d{4})\\d", "Q"),
    tri = zoo::as.yearqtr(quarter) %>% as.Date()
  ) %>% 
  ggplot(aes(tri, taxa_des)) + 
    geom_line() + 
    scale_x_date(
      breaks = scales::breaks_width("3 month", offset = -30),
      labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y"),
      limits = c(as.Date("2019-01-01"), as.Date("2020-10-01"))
    )
df
```
```{r} 

# Rendimentos - Tocantins
rendi <- get_sidra(
  x = 5439,
  geo = "State",
  header = T,
  period = "201201-202004"
) %>% janitor::clean_names()

rendimento_to <- rendi %>%
  filter(unidade_da_federacao == "Tocantins", posicao_na_ocupacao_no_trabalho_principal == "Total", unidade_de_medida == "Reais", variavel == "Rendimento médio real do trabalho principal, efetivamente recebido no mês de referência, pelas pessoas de 14 anos ou mais de idade, ocupadas na semana de referência, com rendimento de trabalho") %>% 
  mutate(quarter = trimestre_codigo %>% stringr::str_replace("(?<=\\d{4})\\d", "Q"),
    tri = zoo::as.yearqtr(quarter) %>% as.Date()) 




#Rendimentos - Brasil

rendi_br <- get_sidra(
  x = 5439,
  header = T,
  period = "201201-202004"
) %>% janitor::clean_names()

rendimento_brasil <- rendi_br %>% 
  filter(nivel_territorial == "Brasil", posicao_na_ocupacao_no_trabalho_principal == "Total", unidade_de_medida == "Reais", variavel == "Rendimento médio real do trabalho principal, efetivamente recebido no mês de referência, pelas pessoas de 14 anos ou mais de idade, ocupadas na semana de referência, com rendimento de trabalho") %>% 
  mutate(quarter = trimestre_codigo %>% stringr::str_replace("(?<=\\d{4})\\d", "Q"),
    tri = zoo::as.yearqtr(quarter) %>% as.Date())


# Rendimento - Norte

rendi_norte <- get_sidra(
  x = 5439,
  header = T,
  geo = "Region",
  period = "201201-202004"
) %>% janitor::clean_names()

rendimento_norte <- rendi_norte %>% 
  filter(grande_regiao == "Norte", unidade_de_medida == "Reais", posicao_na_ocupacao_no_trabalho_principal == "Total", variavel == "Rendimento médio real do trabalho principal, efetivamente recebido no mês de referência, pelas pessoas de 14 anos ou mais de idade, ocupadas na semana de referência, com rendimento de trabalho") %>% 
  mutate(quarter = trimestre_codigo %>% stringr::str_replace("(?<=\\d{4})\\d", "Q"),
    tri = zoo::as.yearqtr(quarter) %>% as.Date())


# Gráficos

ggplot() + geom_line(rendimento_to, mapping = aes(tri, valor, colour = "Tocantins")) + geom_line(rendimento_brasil, mapping = aes(tri, valor, colour = "Brasil")) + geom_line(rendimento_norte, mapping = aes(tri, valor, colour = "Região Norte")) + scale_color_manual(values = petgg::colors[1:3]) +
  scale_x_date(
      breaks = scales::breaks_width("3 month", offset = -30),
      labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y"),
      limits = c(as.Date("2019-01-01"), as.Date("2020-10-01"))
    )





```
