---
output: latex_fragment
---

```{r setup, include=F, message=F, warning=F}
library(tidyverse)
library(knitr)
library(scales)
library(zoo)
library(ipeadatar)
library(petgg)
library(extrafont)
library(kableExtra)
petgg::set_theme(base_family = "EB Garamond")

knitr::opts_chunk$set(
	echo = FALSE,
	eval = TRUE,
	fig.path = "fig/",
	message = FALSE,
	warning = FALSE,
	dev = "cairo_pdf",
	dpi = 300
)
m <- 1000
M <- 1000000
B <- 1000000000
```

```{r saldo}
# Saldo de Empregos Norte e Tocantins

tibble(
	`Região Norte` = c(2764,10419,-6370,-30747,-11146,6093,16015,22483,20640, 20658),
	Tocantins = c(199,1482,-86,-2850,-1251,1240,1810,2096,1790,1504),
	mes = c("jan","fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out")
) %>% 
	pivot_longer(!mes, names_to = "local", values_to = "saldo") %>% 
	ggplot(aes(factor(mes, levels = c("jan","fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out")), saldo, fill = local)) +
	geom_bar(stat = "identity", position = "dodge") +
	scale_y_continuous(labels = function(n) n/m)
```

```{r saldo_setor_to}
# Saldo por Setores no Tocantins
tibble(
	Saldo = c(277,109,961,-1950,-660), 
	Setores = c("Agricultura","Indústrias", "Construção", "Comércio", "Serviços")
) %>% 
	ggplot(aes(Setores, Saldo)) +
	geom_bar(stat = "identity") +
	scale_y_continuous(labels = function(n) n/m)
```

```{r tx_desemprego_to}
# Taxa de desemprego trimestral
ipeadatar::ipeadata("PNADC_TXDES_UF") %>% 
	filter(tcode == 17) %>% 
	ggplot(aes(date, value)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
    xmax = as.Date("2019-04-01"),
    ymin = -Inf,
    ymax = Inf,
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf
	) +
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = scales::label_number(suffix = "%", accuracy = 1))
```

```{r pedido_segudo_desem}
# Pedidos Seguro desemprego trimestral

tibble(
	value = c(9833, 9833, 8832, 8784, 9642, 9324, 9155, 8182, 8785, 10642),
	trimestre = seq(as.Date("2018-01-01"), as.Date("2020-06-01"), by = "quarter")
) %>% 
	ggplot(aes(trimestre, value)) +
	geom_line() +
	scale_y_continuous(labels = function(x) x/m) +
	scale_x_date(
		breaks = scales::breaks_width("90 day"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	)
```

```{r pop_ocupada}
# População Ocupada - Tocantins Trimestral
# Força de Trabalho - Taxa de Participação
ipeadatar::ipeadata("PNADC_TXPARTFT_UF") %>% 
	filter(tcode == 17) %>% 
	ggplot(aes(date, value)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
		xmax = as.Date("2019-04-01"),
		ymin = -Inf,
		ymax = Inf
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf
	) + 
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = scales::label_number(suffix = "%", accuracy = 1))
```

```{r rend_medio}
# Rendimento médio real - trab. principal - habitual - mensal
# Trimestral
ipeadatar::ipeadata("PNADC_RENDREALPRINCHAB_UF", language = "br") %>% 
	filter(tcode %in% c(0,1,17)) %>% 
	select(date, value, uname) %>% 
	mutate(uname = case_when(
		uname == "Brasil" ~ "Brasil",
		uname == "Regiões" ~ "Região Norte",
		uname == "Estados" ~ "Tocantins"
	)) %>% 
	ggplot(aes(date, value, colour = uname)) +
	geom_rect(
		xmin = as.Date("2019-01-01"),
		xmax = as.Date("2019-04-01"),
		ymin = -Inf,
		ymax = Inf,
		colour = NA
	) +
	geom_rect(
		xmin = as.Date("2019-10-01"),
		xmax = as.Date("2020-01-01"),
		ymin = -Inf,
		ymax = Inf,
		colour = NA
	) + 
	geom_line() +
	scale_x_date(
		breaks = scales::breaks_width("9 month"),
		labels = function(x) zoo::format.yearqtr(x, "%qT\n%Y")
	) +
	scale_y_continuous(labels = function(x) x/m)
```

```{r}
# Tabelas

caged_idade <- tibble(
  carac = c("14-34", "35-65", "65+"),
  Admitidos = c(12933, 5270, 21),
  Demitidos = c(11375, 5677, 59),
  Saldo = Admitidos - Demitidos
)
caged_sexo <- tibble(
  carac = c("Homem", "Mulher"),
  Admitidos = c(11043, 6243),
  Demitidos = c(10869, 5736),
  Saldo = Admitidos - Demitidos
)
bind_rows(caged_idade, caged_sexo) %>% 
	kable(
		caption = "XXX",
		align = "lrrr",
		format.args = list(big.mark = ".", decimal.mark = ",", scientific = FALSE),
		booktabs = T,
		col.names = c("", "Admitidos", "Demitidos", "Saldo")
	) %>% 
	kable_styling(full_width = T) %>% 
	pack_rows("Idade", 1, 3) %>% 
	pack_rows("Sexo", 4, 5)
```