---
output: latex_fragment
---

```{r setup, include=F, message=F, warning=F}
library(tidyverse)
library(sidrar)
library(rmarkdown)
library(knitr)
library(scales)
library(petgg)
library(extrafont)

petgg::set_theme(base_family = "EB Garamond")

knitr::opts_chunk$set(
	echo = FALSE,
	eval = TRUE,
	fig.path = "fig/",
	message = FALSE,
	warning = FALSE,
	dpi = 300,
	dev = "cairo_pdf"
)
m <- 1000
M <- 1000000
B <- 1000000000

# converte AAAAMM para formato MT/AAAA
triForm <- function(x) paste0(substr(x, 6, 6),"T\n",substr(x, 1, 4))
```

```{r producao, include=T}
# Produção - Tocantins 2020

# Os produtos são Arroz, milho 1 safra, milho 2 safra, soja, cana de açucar e mandioca
produtos <- c(39432, 39441, 39442, 39443, 39456, 39467)

# Série histórica da estimativa anual da área plantada, área colhida, produção e rendimento médio dos produtos das lavouras
prod <- get_sidra(x = 6588,
									variable = 35,
									period =  "202012",
									header = TRUE,
									geo = "State",
									geo.filter = list("State" = 17),
									format = 4)

prod %>%
	filter(
		`Mês (Código)` == "202012",
		`Produto das lavouras (Código)` %in% produtos
	) %>%
	transmute(
		produto = `Produto das lavouras`,
		valor = Valor
	) %>%
	mutate(
		produto = str_extract(produto, ".[a-z]+")
	) %>%
	group_by(produto) %>%
	summarise(total = sum(valor)) %>%
	ggplot() +
	geom_bar(aes(x = produto, y = total), stat = "identity") +
	scale_y_continuous(labels = function(n) n/M)

```

```{r rendim_medio}
rend_medio <- get_sidra(x = 6588,
											 variable = 36,
											 period = "202012",
											 geo = "State",
											 geo.filter = list("State" = 17),
											 header = TRUE,
											 format = 4)

rend_medio %>% 
	filter(`Produto das lavouras (Código)` %in% produtos) %>% 
	transmute(
		produto = `Produto das lavouras`,
		valor = Valor
	) %>%
	mutate(
		produto = str_extract(produto, ".[a-z]+")
	) %>%
	group_by(produto) %>%
	summarise(total = sum(valor)) %>%
	ggplot() +
	geom_bar(aes(x = produto, y = total), stat = "identity") +
	scale_y_continuous(labels = function(n) n/m)
```

```{r area_plantada}
# Área Plantada
area_plan <- get_sidra(x = 6588,
											 variable = 216,
											 period = "202012",
											 geo = "State",
											 geo.filter = list("State" = 17),
											 header = TRUE,
											 format = 4)

area_plan %>%
	filter(`Produto das lavouras (Código)` %in% produtos) %>%
	transmute(
		produto = `Produto das lavouras`,
		valor = Valor
	) %>%
	mutate(
		produto = str_extract(produto, ".[a-z]+")
	) %>%
	group_by(produto) %>%
	summarise(total = sum(valor)) %>%
	ggplot() +
	geom_bar(aes(x = produto, y = total), stat = "identity") +
	scale_y_continuous(labels = function(n) n/m)
```
```{r prod_leite}
# tibble(
# 	litros=c(33189, 32958, 29721, 36369, 37273),
#   trimestre=c("1T/2019","2T/2019", "3T/2019", "4T/2019", "1T/2020")
# ) %>%
# 	ggplot() +
# 	geom_bar(aes(factor(trimestre, levels = trimestre), litros), stat = "identity") +
# 	scale_y_continuous(labels = function(n) n/m)
```


```{r abate_total}
# Abate de animais - Tocantins

# abate_total <- get_sidra(x = 1092,
# 												 variable = 284,
# 												 period = c("201904", "202001", "202002", "202003"),
# 												 geo = "State",
# 												 geo.filter = list("State" = 17),
# 												 header = TRUE,
# 												 format = 4)
# 
# abate_total %>% 
#   filter(
#   	`Tipo de inspeção` == "Total",
#   	`Referência temporal` == "Total do trimestre",
#   	`Tipo de rebanho bovino` == "Total"
#   ) %>% 
# 	mutate(data = triForm(`Trimestre (Código)`)) %>% 
# 	ggplot() +
# 	geom_bar(
# 		aes(factor(data, levels = c("4T/2019", "1T/2020", "2T/2020", "3T/2020")), Valor), 
# 		stat = "identity"
# 	) +
# 	scale_y_continuous(labels = function(n) n/m)
```


```{r abates}
# Abate de frangos, bovinos, vacas por trimestre
# Unidade em Cabeças
abate_bovino <- get_sidra(
		x = 1092,
		period = c("202001", "202002", "202003", "202004"),
		geo = "State",
		geo.filter = list("State" = 17),
		header = TRUE,
		format = 4
	) %>% filter(
		`Tipo de rebanho bovino` %in% c(
			"Novilhos",
			"Novilhas",
			"Bois",
			"Vacas"
		),
		`Referência temporal` == "Total do trimestre",
		`Tipo de inspeção` == "Total",
		`Variável` == "Animais abatidos"
	) %>% 
	select(`Trimestre (Código)`, `Tipo de rebanho bovino`, Valor)
	
# Unidade em cabeças
abate_frango <- get_sidra(x = 1094,
		period = c("202001", "202002", "202003", "202004"),
		geo = "State",
		geo.filter = list("State" = 17),
		header = TRUE,
		format = 4
	) %>% filter(
		`Referência temporal` == "Total do trimestre",
		`Tipo de inspeção` == "Total",
		`Variável` == "Animais abatidos"
	) %>% 
	select(`Trimestre (Código)`, Valor)

bind_rows(
	abate_bovino %>% mutate(tipo = `Tipo de rebanho bovino`),
	abate_frango %>% mutate(tipo = "Frango")
) %>% 
	select(`Trimestre (Código)`, tipo, Valor) %>% 
	drop_na() %>% 
	mutate(tri = triForm(`Trimestre (Código)`)) %>% 
	ggplot(aes(factor(tri, levels = c("1T\n2020", "2T\n2020", "3T\n2020", "4T\n2020")), Valor, fill = tipo)) +
	geom_bar(stat = "identity", position = "dodge") +
	scale_y_continuous(labels = function(n) n/m)
```
```{r galinha_poedeiras}

# prod_galinhas <- get_sidra(
# 	x = 915,
# 	period = c("201904", "202004", "202001", "202002", "202003"),
# 	geo = "State",
# 	geo.filter = list("State" = 17),
# 	header = TRUE,
# 	format = 4
# )
# 
# # Cabeça
# prod_galinhas %>% 
# 	filter(
# 		Variável == "Número de cabeças de galinhas poedeiras nos estabelecimentos agropecuários",
# 		`Referência temporal` == "Total do trimestre"
# 	) %>% 
# 	mutate(data = triForm(`Trimestre (Código)`)) %>% 
# 	ggplot() +
# 	geom_bar(
# 		aes(factor(data, levels = c("4T/2019", "1T/2020", "2T/2020", "3T/2020")), Valor),
# 		stat = "identity"
# 	) +
# 	scale_y_continuous(labels = function(n) n/M)
```

```{r ovos_galinha}
# Quantidade de ovos produzidos, Mil dúzias

# prod_galinhas %>% 
# 	filter(
# 		Variável == "Quantidade de ovos produzidos",
# 		`Referência temporal` == "Total do trimestre"
# 	) %>% 
# 	mutate(data = triForm(`Trimestre (Código)`)) %>% 
# 	ggplot() +
# 	geom_bar(
# 		aes(factor(data, levels = c("4T/2019", "1T/2020", "2T/2020", "3T/2020")), Valor),
# 		stat = "identity"
# 	)
```

